const SUPABASE_URL = 'https://eaipmgajwktqkvhfnbpj.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhaXBtZ2Fqd2t0cWt2aGZuYnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTAzMjAsImV4cCI6MjA2MjI4NjMyMH0.v8H7mpcijqeLMuUhHf8JzHwL8uo9eVFA5hfjLzVfauE';
const PYTHON_BACKEND_URL = 'https://agario-python-ai.onrender.com';
const PYTHON_BACKEND_TIMEOUT = 50000;

const GameConfig = {
    WORLD_WIDTH: 3000,
    WORLD_HEIGHT: 3000,
    MAX_FOOD_PELLETS: 150,
    MAX_VIRUSES: 10,
    FOOD_RADIUS: 7,
    VIRUS_RADIUS: 50,
    PLAYER_INITIAL_RADIUS: 15,
    PLAYER_MIN_RADIUS_SPLIT: 25,
    PLAYER_MIN_RADIUS_EJECT: 20,
    PLAYER_MAX_CELLS: 16,
    CELL_BASE_SPEED: 4.0, // Slightly increased base speed
    // Speed = BASE / (1 + (Radius / FACTOR)) - adjust factor
    CELL_SPEED_RADIUS_FACTOR: 70, // Speed decreases relative to radius increase
    CELL_FRICTION_AIR: 0.05, // Increased friction for more Agar.io-like slowdown
    EJECTED_MASS_RADIUS: 6,
    EJECTED_MASS_SPEED: 15, // Speed for setVelocity impulse
    EJECTED_MASS_FRICTION_AIR: 0.03,
    EJECTED_MASS_LIFESPAN: 20 * 1000,
    EJECT_SELF_COLLISION_COOLDOWN: 1000,
    SPLIT_VELOCITY_IMPULSE: 7, // Velocity impulse factor when splitting
    MERGE_COOLDOWN_BASE: 15 * 1000,
    MERGE_COOLDOWN_PER_MASS_FACTOR: 0.01,
    BOT_COUNT: 10,
    PYTHON_BOT_UPDATE_INTERVAL: 1000,
    CAMERA_SMOOTHING: 0.08,
    CAMERA_ZOOM_BASE_VIEW: 800,
    MAX_ZOOM_OUT: 0.25,
    MIN_ZOOM_IN: 1.5,
    LEADERBOARD_UPDATE_INTERVAL: 2000,
    MULTIPLAYER_UPDATE_INTERVAL: 100,
    MULTIPLAYER_DEAD_RECKONING_THRESHOLD: 200,
    STALE_PLAYER_CLEANUP_INTERVAL: 60 * 1000,
    STALE_PLAYER_THRESHOLD: 2 * 60 * 1000,
    OBJECT_SPAWN_ATTEMPT_INTERVAL: 2000,
};